version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Replace with your MongoDB Atlas URI
      - MONGODB_URI=${MONGODB_URI}
      # Allow Socket.IO and REST CORS from these origins (comma-separated)
      - SOCKETIO_CORS_ORIGINS=${SOCKETIO_CORS_ORIGINS:-https://fraudsense-frontend.fauzanazz.com}
      # Optional: configure model endpoints if used
      - SAILOR2_ENDPOINT=${SAILOR2_ENDPOINT}
      - QWEN2_AUDIO_ENDPOINT=${QWEN2_AUDIO_ENDPOINT}
      # Fraud analysis knobs
      - FRAUD_ANALYSIS_DEBOUNCE=${FRAUD_ANALYSIS_DEBOUNCE:-3000}
      - ENABLE_REAL_TIME_ALERTS=${ENABLE_REAL_TIME_ALERTS:-true}
      - STORE_FRAUD_RESULTS=${STORE_FRAUD_RESULTS:-true}
      # Server port
      - PORT=3001
    expose:
      - "3001"
    labels:
      - "traefik.enable=true"
      # Set your domain if exposing via Traefik; otherwise remove labels
      - "traefik.http.routers.fraudsense-backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.fraudsense-backend.entrypoints=websecure"
      - "traefik.http.routers.fraudsense-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.fraudsense-backend.loadbalancer.server.port=3001"
    networks:
      - dokploy-network

  turn:
    image: instrumentisto/coturn:4.6.2
    container_name: fraudsense-turn
    restart: unless-stopped
    command:
      - -n
      - --log-file=stdout
      - --lt-cred-mech
      - --realm=${TURN_REALM}
      - --server-name=${TURN_DOMAIN}
      - --user=${TURN_USER}:${TURN_PASSWORD}
      - --fingerprint
      - --listening-port=3478
      - --external-ip=${TURN_PUBLIC_IP}
      - --min-port=${TURN_MIN_PORT:-49152}
      - --max-port=${TURN_MAX_PORT:-49999}
      - --no-tls
      - --no-cli
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "49152-49999:49152-49999/udp"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.udp.routers.fraudsense-turn-udp.entrypoints=turn-udp"
      - "traefik.udp.routers.fraudsense-turn-udp.service=fraudsense-turn-udp"
      - "traefik.udp.services.fraudsense-turn-udp.loadbalancer.server.port=3478"
      - "traefik.tcp.routers.fraudsense-turn-tcp.entrypoints=turn-tcp"
      - "traefik.tcp.routers.fraudsense-turn-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.fraudsense-turn-tcp.service=fraudsense-turn-tcp"
      - "traefik.tcp.services.fraudsense-turn-tcp.loadbalancer.server.port=3478"

networks:
  dokploy-network:
    external: true


